### PR TITLE
Updated sass-director.js

### PR DESCRIPTION
**Pull request by jonathantneal**
Major changes:
- Added `--sass`, `--no-underscore-options`, and `--watch` options
- Removed `<base-directory>` option

### CODE REVIEW

**Comment by jonathantneal** [comment]
When you’re available, I would prefer a second set of eyes on this.

**Comment by una** [comment]
Hey Jon! Awesome work :) Seriously. The flags --sass and --no-underscore work great :+1:

I found a few problems with the --watch flag, however
1.  When re-saving the main.scss file with no changes made, it toggles the state of all of the files.

sassdirector-watchbug

Here's another instance:

sassdirector-watchbug2

I also noticed that this is not a problem when there is content inside of the file (if there's some styling in there)
1. I would specify "Created folder <foldername/>" and "Created file <_filename.scss>" to differentiate them when logging actions in the console.
2. Maybe log an error when the incorrect @import statement is presented (i.e. `@import file` without the quotations or missing a semicolon)

**Comment by una** [comment]
@jonathantneal are you looking at this still?

**Comment by jonathantneal** [comment]
Yes, I’ve been focused on some other projects, and I will give this some love soon.

**Comment by una** [comment]
No problem :) Keep on kicking ass

**Comment by jonathantneal** [comment]
You know, I think that other work got the best of me. Thanks for all the kind words. I’m going to go ahead and close this stale branch, now that I’ve found the centralized **pulls** section on GitHub. You keep on being awesome. 😄

**Pull request closed without merging**
