### PR TITLE
Add sass-director.sh

### PR DESCRIPTION
**Pull request by jonathantneal**
This is only the initial version, but it is fully functional.

```
Usage: sass-director <manifest-file> <base-directory>
```

### CODE REVIEW

**Comment by una** [comment]
Can you give a bit of documentation on how to execute this shell file?

**Comment by jonathantneal** [comment]
Okay, I’ve created a Node version that you can test locally.

``` sh
cd sass-director
npm install -g
```

Now you can test it as you’ve described.

``` sh
cd ~/some-project
sass-director main.scss sass
```

---

As for the pure bash file, you would need to source it bash file your Terminal.

``` sh
cd sass-director
source sass-director.sh
```

Then you could test it as you’ve described.

``` sh
cd ~/some-project
sass-director main.scss sass
```

I hope having this version and a Node version mean anybody can use sass-director. These are a functional start, but I’m sure we could begin to add more features, like the prefix and suffix options you have on http://sassdirector.com/

**Comment by una** [comment]
Awesome! Thanks for all the work on this :) In practice, I'm getting an error when using subdirectories:

```
➜  sass-director git:(feature/sass-director-cli) ✗ sass-director test/main.scss sass/

fs.js:647
  return binding.mkdir(pathModule._makeLong(path),
                 ^
Error: ENOENT, no such file or directory 'sass//dir2/dir3'
    at Object.fs.mkdirSync (fs.js:647:18)
    at mkdir (/usr/local/lib/node_modules/sass-director/sass-director.js:19:6)
    at /usr/local/lib/node_modules/sass-director/sass-director.js:75:3
    at Array.forEach (native)
    at /usr/local/lib/node_modules/sass-director/sass-director.js:74:20
    at fs.js:271:14
    at Object.oncomplete (fs.js:107:15)
```

For reference, the test main.scss file is:

```
@import "dir1/file1"
@import "dir2/dir3/file2"

@import "dir4/dir5/file3" 
```

**Comment by jonathantneal** [comment]
Thanks for the quick feedback. I’ve committed a fix for this.

**Comment by una** [comment]
Awesome!  Its almost there! A few things:
1. Errors out when the first line is a comment or is empty.
2. If I want to create the files in the same folder as main.scss, i would want the expected input to be `sass-director main.scss` with an optional 3rd argument. The optional argument should signal for the files to be created in the current directory.

**Comment by jonathantneal** [comment]
1. Would you share the new failing CSS manifest file and the error?
2. Are you saying that when the base directory is not specified, it should default to the current working directory and not the directory of the manifest file? If so, I can make that change as well.

Currently, if you do not specify a base directory, it uses the directory of the manifest file.

``` sh
sass-director manifest-directory/main.scss
```

And we’ll imagine the contents of the `main.scss` file.

``` scss
@import "sub-directory/my-partial"
```

So, currently, the generated file would be `manifest-directory/sub-directory/_my-partial.scss`.

**Comment by una** [comment]
Yep! Sorry I didn't include it earlier.

1: This would fail if there was an extra line above the first import statement, like so:

```

@import "utils/variables";
@import "utils/functions";
@import "utils/mixins";
@import "utils/placeholders";

@import "base/reset";
@import "base/typography";

@import "layout/navigation";
@import "layout/grid";
```

2: Here's the error I was talking about (within the folder containing main.scss):

```
➜  temp-test  sass-director main.scss  

fs.js:647
  return binding.mkdir(pathModule._makeLong(path),
                 ^
Error: EEXIST, file already exists 'main.scss'
    at Object.fs.mkdirSync (fs.js:647:18)
    at mkdir (/usr/local/lib/node_modules/sass-director/sass-director.js:21:6)
    at Object.<anonymous> (/usr/local/lib/node_modules/sass-director/sass-director.js:46:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

Same error for `sass-director main.scss /`

**Comment by jonathantneal** [comment]
I do not get an error when using the file you provided and run:

``` sh
sass-director main.scss
```

But I do get the error when specifying the root folder as my base directory.

``` sh
sass-director main.scss /
```

I’ll look into this. By default you should provided get an error about access to the root `/` directory.

**Comment by jonathantneal** [comment]
Okay, a fix has been committed! Freshly checkout this pull out and let me know if things are resolved.

**Comment by una** [comment]
This works wonderfully!! Thank you for whipping it up so quickly!

I'm going to merge this in tonight when I have a chance to refactor the repo and separate the public facing site from the module.

**Comment by jonathantneal** [comment]
Hurray! :cake:

**Comment by una** [comment]
:) Lets publish that package! :smile:

**Comment by jonathantneal** [comment]
Would you like to do that? I’m happy to help in anyway, but it also might be fun for you to do! =)

**Comment by una** [comment]
Haha sure :) done! And the docs are updated

**Pull request merged**
